name: CI

on:
  push:
    branches: ["batch-changes/**"]
  pull_request:
    branches: [main, "batch-changes/**"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: exit 1
